# Generated by Django 3.0.5 on 2021-02-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='chapters',
            field=models.ManyToManyField(to='pages.Chapter', verbose_name='Capítulo'),
        ),
    ]
